spring:
  application:
    name: test

  # DB設定
  datasource:
    url: jdbc:postgresql://localhost:5432/mall_db
    username: admin
    password: admin

  # Hibernate / JPA 設定
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway 設定
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
